<fieldset class="fieldset create account">
    <legend class="legend"><span><?php /* @escapeNotVerified */echo __('Additional Information') ?></span></legend><br>
    <div class="field is_vendor">
        <div class="control">
            <input type="checkbox" name="is_approved" id="is_approved"value="1" title="Become a Vendor"autocomplete="off"><span>Become a vendor</span>
        </div>
    </div>
</fieldset>